### ISSUE TITLE
建议增加auth认证防止被黄网白嫖

### ISSUE THREAD

**Issue by ZhiXuanWang** [ifyour/cf-image-hosting#4]
参考：https://hono.dev/getting-started/cloudflare-workers#using-variables-in-middleware

import { Hono } from "hono";
import { serveStatic } from "hono/cloudflare-workers";
import { basicAuth } from 'hono/basic-auth'

const app = new Hono<{ Bindings: { API_HOST: string, USERNAME: string, PASSWORD: string, whiteList : Array<string> } }>();
app.use('/', async (c, next) => {
  const auth = basicAuth({
    username: c.env.USERNAME,
    password: c.env.PASSWORD,
  })
  return auth(c, next)
});

app.get("/*", serveStatic({ root: "./public" }));

app.post("/upload", async (c) => {
  const body = await c.req.parseBody();
  const formData = new FormData();
  // Telegraph ignores filenames, so we can use any filename we want!
  formData.append("file", body.file as Blob, "test.png");
  return fetch(`${c.env.API_HOST}/upload`, {
    method: "POST",
    body: formData,
  });
});

app.get("/file/:fileName", async (c) => {
  const referrer = c.req.header('Referer') || '';
  const url = referrer.split('/')[2] || '';
  const min_ulr = url.split(':')[0] || '';
  if(referrer && c.env.whiteList.includes(min_ulr) || !referrer) {
    // 访问域名在白名单内，放行 !referer表示直接访问图片(比如浏览器地址栏输入图片地址)
    return fetch(`${c.env.API_HOST}/file/${c.req.param("fileName")}`);
  } else {
    return fetch('https://pic.diydoutu.com/bq/1061.jpg');
  }
});

export default app;

**Comment by ifyour** [comment]
暂时没有计划支持，你可以 fork 一份自己实现部署一个？ 😂

**Comment by ZhiXuanWang** [comment]
> 暂时没有计划支持，你可以 fork 一份自己实现部署一个？ 😂

按照大佬指导已完成：https://github.com/ZhiXuanWang/cf-image-hosting/tree/img

**Comment by ZhiXuanWang** [comment]
name = "cf-image-hosting"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[env.dev.vars]
API_HOST = "https://telegraph.mingming.dev"
USERNAME = "admin"
PASSWORD = "admin"
whiteList = ['localhost', 'abc.com', '123.com']

[env.prod.vars]
API_HOST = "https://telegra.ph"
USERNAME = "admin"
PASSWORD = "123456"
whiteList = ['img.164746.xyz', '164746.xyz', '1024it.eu.org']

[site]
bucket = "./src"
